oferta_homepage:
    path:     /hello/{name}
    defaults: { _controller: OfertaBundle:Default:index }

ciudad_cambiar:
    path: /ciudad/cambiar-a-{ciudad}
    defaults: { _controller: CiudadBundle:Default:cambiar }
    requirements:        
        ciudad: .+